export const currencies = [
  {
    currencyName: "USD - US Dollar",
    short: "USD",
    Symbol: "&#36",
    flag: "./roundFlags/roundUS.png",
  },
  {
    currencyName: "EUR - Europian Euro",
    short: "EUR",
    Symbol: "&#8364;",
    flag: "./roundFlags/roundEU.png",
  },
  {
    currencyName: "GBP - British Pound",
    short: "GBP",
    Symbol: "&pound",
    flag: "./roundFlags/roundUK.png",
  },
  {
    currencyName: "JPY - Japanese Yen",
    short: "JPY",
    Symbol: "&#165",
    flag: "./roundFlags/roundJAP.png",
  },
  {
    currencyName: "CAD - Canadian Dollar",
    short: "CAD",
    Symbol: "&#36",
    flag: "./roundFlags/roundCA.png",
  },
  {
    currencyName: "CZK - Czech Koruna",
    short: "CZK",
    Symbol: "Kč",
    flag: "./roundFlags/roundCZ.png",
  },
  {
    currencyName: "BGN - Bulgarian Lev",
    short: "BGN",
    Symbol: "Лв.",
    flag: "./roundFlags/roundBGN.png",
  },
  {
    currencyName: "DKK - Danish Krone",
    short: "DKK",
    Symbol: "Kr",
    flag: "./roundFlags/roundDKK.png",
  },
  {
    currencyName: "HUF - Hungarian  Forint",
    short: "HUF",
    Symbol: "Ft",
    flag: "./roundFlags/roundHUF.png",
  },
  {
    currencyName: "PLN - Polish Złoty ",
    short: "PLN",
    Symbol: "zł",
    flag: "./roundFlags/roundPLN.png",
  },
  {
    currencyName: "RON - Romanian Leu ",
    short: "RON",
    Symbol: "lei",
    flag: "./roundFlags/roundRON.png",
  },
  {
    currencyName: "SEK - Swedish Krona ",
    short: "SEK",
    Symbol: "kr",
    flag: "./roundFlags/roundSEK.png",
  },
  {
    currencyName: "CHF - Swiss Franc ",
    short: "CHF",
    Symbol: "SFr",
    flag: "./roundFlags/roundCHF.png",
  },
  {
    currencyName: "ISK - Icelandic Króna ",
    short: "ISK",
    Symbol: "Íkr",
    flag: "./roundFlags/roundISK.png",
  },
  {
    currencyName: "NOK - Norwegian Krone ",
    short: "NOK",
    Symbol: "kr",
    flag: "./roundFlags/roundNOK.png",
  },
  {
    currencyName: "HRK - Croatian Kuna ",
    short: "HRK",
    Symbol: "kn",
    flag: "./roundFlags/roundHRK.png",
  },
  {
    currencyName: "RUB - Russian Ruble ",
    short: "RUB",
    Symbol: "₽",
    flag: "./roundFlags/roundRUB.png",
  },
  {
    currencyName: "TRY - Turkish Lira ",
    short: "TRY",
    Symbol: "₺",
    flag: "./roundFlags/roundTRY.png",
  },
  {
    currencyName: "AUD - Australian Dollar ",
    short: "AUD",
    Symbol: "AUD",
    flag: "./roundFlags/roundAUD.png",
  },
  {
    currencyName: "BRL - Brazilian Real ",
    short: "BRL",
    Symbol: "R$",
    flag: "./roundFlags/roundBRL.png",
  },
  {
    currencyName: "CNY - Chinese Yuan ",
    short: "CNY",
    Symbol: "¥",
    flag: "./roundFlags/roundCNY.png",
  },
  {
    currencyName: "HKD - Hong Kong Dollar ",
    short: "HKD",
    Symbol: "元",
    flag: "./roundFlags/roundHKD.png",
  },
  {
    currencyName: "IDR - Indonesian Rupiah ",
    short: "IDR",
    Symbol: "Rp",
    flag: "./roundFlags/roundIDR.png",
  },
  {
    currencyName: "ILS - Israeli New Shekel ",
    short: "ILS",
    Symbol: "₪",
    flag: "./roundFlags/roundILS.png",
  },
  {
    currencyName: "INR - Indian Rupee ",
    short: "INR",
    Symbol: "₹",
    flag: "./roundFlags/roundINR.png",
  },
  {
    currencyName: "KRW - South Korean Won ",
    short: "KRW",
    Symbol: "₩",
    flag: "./roundFlags/roundKRW.png",
  },
  {
    currencyName: "MXN - Mexican Peso ",
    short: "MXN",
    Symbol: "$",
    flag: "./roundFlags/roundMXN.png",
  },
  {
    currencyName: "MYR - Mexican Peso ",
    short: "MYR",
    Symbol: "RM",
    flag: "./roundFlags/roundMYR.png",
  },
  {
    currencyName: "NZD - New Zealand Dollar ",
    short: "NZD",
    Symbol: "$",
    flag: "./roundFlags/roundNZD.png",
  },
  {
    currencyName: "PHP - Philippine peso ",
    short: "PHP",
    Symbol: "₱",
    flag: "./roundFlags/roundPHP.png",
  },
  {
    currencyName: "SGD - Singapore Dollar ",
    short: "SGD",
    Symbol: "S$",
    flag: "./roundFlags/roundSGD.png",
  },
  {
    currencyName: "THB - Singapore Dollar ",
    short: "THB",
    Symbol: "฿",
    flag: "./roundFlags/roundTHB.png",
  },
  {
    currencyName: "ZAR - South African Rand ",
    short: "ZAR",
    Symbol: "R",
    flag: "./roundFlags/roundZAR.png",
  },
];
